import './globals.css';
import { Inter } from 'next/font/google';

import { AuthProvider } from '@/context/auth';
import { ThemeProvider } from '@/components/providers/theme-provider';

import { Header } from '@/components/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    enableSystem={false}
                    storageKey="nf-theme"
                >
                    <AuthProvider>
                        <Header />{children}
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
