name: Format code # ワークフローの名前を指定

on: # トリガー条件を指定
    pull_request: # プルリクエストに反応
        types: [opened, synchronize] # プルリクエストがオープン、更新された場合にトリガー

jobs: # ジョブの定義を開始
    formatter: # ジョブ名を指定
        name: formatter # ジョブの名前
        runs-on: ubuntu-latest # Ubuntu Linux 上で実行
        steps:
            - uses: actions/checkout@v2
            - name: Install packages
              run: npm ci
            - name: Prettier
              run: npm run format
            - name: Lint
              run: npm run lint
