name: Format code # ワークフローの名前を指定

on: # トリガー条件を指定
    pull_request: # プルリクエストに反応
        types: [opened, synchronize] # プルリクエストがオープン、更新された場合にトリガー

jobs: # ジョブの定義を開始
    formatter: # ジョブ名を指定
        name: node-formatter # ジョブの名前
        runs-on: ubuntu-latest # Ubuntu Linux 上で実行
        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run format
            - run: npm run lint
